---
- name: update rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git dest={{ rbenv_root }}

- name: set environment variable to .zshrc
  lineinfile: dest=~/.zshrc regexp="export RBENV_ROOT" line='export RBENV_ROOT="{{ rbenv_root }}"'

- name: add the environment variable to path
  lineinfile: dest=~/.zshrc regexp="RBENV_ROOT/bin" line='export PATH="$RBENV_ROOT/bin:$PATH"'

- name: add rbenv initialization to .zshrc
  lineinfile: dest=~/.zshrc regexp="eval" line='eval "$(rbenv init -)"'

- name: check ruby-build installed
  command: test -x {{ rbenv_root }}/plugins/ruby-build
  register: rbuild_present
  ignore_errors: yes

- name: clone ruby-build repo
  git: repo=git://github.com/sstephenson/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build
  when: rbuild_present|failed

- name: check ruby {{ ruby_version }} installed
  shell: "{{ rbenv_root }}/bin/rbenv versions | grep {{ ruby_version }}"
  register: ruby_installed
  ignore_errors: yes

- name: install ruby {{ ruby_version }}
  shell: "{{ rbenv_root }}/bin/rbenv install {{ ruby_version }}"
  when: ruby_installed|failed

- name: set global ruby {{ ruby_version }}
  shell: "{{ rbenv_root }}/bin/rbenv global {{ ruby_version }}"
  when: ruby_installed|failed

- name: rehash
  shell: "{{ rbenv_root }}/bin/rbenv rehash"
  when: ruby_installed|failed

- name: set gemrc
  copy: src=gemrc dest=~/.gemrc
